
import ParticlesWrapper from "./_components/ParticlesWrapper"
import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header/Header";

import { PT_Serif } from "next/font/google";

// шрифты для сайта: PT Sans / PT Serif

const pt_serif = PT_Serif({
    subsets: ["latin", "cyrillic"],
    weight: ["400", "700"]
});


export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ru" className="bg-white dark:bg-black text-black dark:text-slate-500 ">
            <body className={`${pt_serif.className} antialiased`}>
                <ParticlesWrapper>
                    <Header />

                    {children}

                </ParticlesWrapper>
            </body>
        </html>
    )
}



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};