
import ParticlesWrapper from "./_components/ParticlesWrapper"
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google"
import "./globals.css";
import Header from "./_components/Header/Header";

// шрифты для сайта: PT Sans / PT Serif

const comfortaa = Comfortaa({
    subsets: ["latin", "cyrillic"],
    weight: ["300", "400", "500"]
});


export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ru" className="bg-white dark:bg-black text-black dark:text-slate-500 ">
            <body className={`${comfortaa.className} antialiased`}>
                <ParticlesWrapper>
                    <Header />

                    {children}

                </ParticlesWrapper>
            </body>
        </html>
    )
}



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};